-- ============================================================
-- kiwe_sampling_2026_1 테이블의 id 컬럼 설정 수정 (Identity 대응)
-- 'is an identity column' 에러 해결 및 자동 번호 생성 보장
-- ============================================================

DO $$ 
BEGIN
    -- 1. id 컬럼이 Identity 컬럼인지 확인
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'kiwe_sampling_2026_1' 
        AND column_name = 'id' 
        AND is_identity = 'YES'
    ) THEN
        -- Identity 컬럼일 경우: 기본값을 직접 SET DEFAULT 할 수 없으므로
        -- GENERATED BY DEFAULT 정책을 확실히 적용하여 비어있을 때 자동 생성을 유도합니다.
        ALTER TABLE kiwe_sampling_2026_1 
            ALTER COLUMN id SET GENERATED BY DEFAULT;
            
        -- (옵션) 시퀀스가 꼬였을 수 있으므로 현재 최대값 다음으로 리셋합니다.
        PERFORM setval(
            pg_get_serial_sequence('kiwe_sampling_2026_1', 'id'), 
            COALESCE((SELECT MAX(id) FROM kiwe_sampling_2026_1), 0) + 1, 
            false
        );
    ELSE
        -- 만약 Identity가 아니라면 (드문 경우), 이전에 계획한 대로 UUID 생성을 시도할 수 있습니다.
        -- 하지만 여기서는 안전하게 확인만 수행합니다.
        RAISE NOTICE 'Column id is not an identity column.';
    END IF;
END $$;

-- 2. (확인용) 컬럼 정보 조회
SELECT column_name, column_default, is_identity, identity_generation
FROM information_schema.columns 
WHERE table_name = 'kiwe_sampling_2026_1' AND column_name = 'id';
